version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.1
jobs:
 
 
  status:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Sending status"
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  heroku_deploy:
    jobs:
      
 
      - status
 
             